version: '3'
services:
    nats:
        image: nats:latest
        networks:
            - couchdb_network
    couchdb_invoker:
        image: docker.io/bluffgnuff/couchdb_invoker:latest
        environment:
            ADDRESS: "172.19.0.2"
            NATSSERVER: "172.19.0.3"
            DB_NAME: "testdb"
            PORT: 5984
            NAME: root
            PASSWORD: root
            TRIGGER: "trigger-command"
            RUST_LOG: "INFO"
        networks:
            - couchdb_network
    stresser:
        image: docker.io/bluffgnuff/stresser:1.1
        environment:
            NATSSERVER: "172.19.0.3"
            TRIGGER: "trigger-command"
            COMMAND: "./CouchGenericFunction"
            COMMAND_ARGS: "--operation Read --table Customers --firstname Mario --lastname Rossi"
            RUST_LOG: "INFO"
        networks:
            - couchdb_network
        depends_on:
            - couchdb_network
networks:
  couchdb_network:
    external:
      name: couchdb_network
# First use:
# - config a DB container
# - docker network connect name_network container_name
# docker-compose -f "Compose MySQLInvoker.yaml" up
