version: '3'
services:
    nats:
        image: nats:latest
        networks:
            - mongo_network
    mongo_invoker:
        image: docker.io/bluffgnuff/mongo_invoker:latest
        environment:
            ADDRESS: "172.20.0.2"
            NATSSERVER: "172.20.0.3"
            DB_NAME: "testDB"
            PORT: 27017
#            NAME: root
#            PASSWORD: root
            TRIGGER: "trigger-command"
            RUST_LOG: "INFO"
        networks:
            - mongo_network
    stresser:
        image: docker.io/bluffgnuff/stresser:1.1
        environment:
            NATSSERVER: "172.20.0.3"
            TRIGGER: "trigger-command"
            COMMAND: "./GenericFunctionWithFlag"
            COMMAND_ARGS: "--db-type Mongo --operation Read --table Customers --firstname Mario --lastname Rossi"
            RUST_LOG: "INFO"
        networks:
            - mongo_network
        depends_on:
            - mongo_invoker
networks:
  mongo_network:
    external:
      name: mongo_network
# First use:
# - config a DB container
# - docker network connect name_network container_name
# docker-compose -f "Compose MySQLInvoker.yaml" up
